
QUESTIONS = {

    # --- Начало осмотра ---
    1: {
        'type': 'standard', 
        'text': 'Проверьте щетки стеклоочистителя', 
        'is_multi_select': True, 
        'fault_options': {
            'pered_lev': 'Передняя левая', 
            'pered_prav': 'Передняя правая', 
            'zad': 'Задняя'
        }, 
        'sub_questions': {
            'text': 
                'Уточните неисправность для "{option_text}":', 
                'options': {
                    'mazhet': 'Мажет', 
                    'otsutstvuet': 'Отсутствует'
                }
            }
        },
    2: {
        'type': 'standard', 
        'text': 'Проверьте подсветку приборов', 
        'fault_options': {
            'free_input': 'Укажите, что не горит'
        }
    },
    3: {
        'type': 'standard', 
        'text': 'Проверьте лампы неисправности на панели приборов', 
        'default_ok': 'Не горят', 
        'default_fault': 'Горят', 
        'is_multi_select': True, 
        'fault_options': {
            'check_engine': 'CHECK ENGINE', 
            'srs': 'SRS', 
            'abs': 'ABS', 
            'akb': 'АКБ'
        }
    },
    4: {
        'type': 'standard', 
        'text': 'Работа стартера при запуске автомобиля', 
        'fault_options': {
            'shum': 'Посторонний шум', 
            'zaklinivanie': 'Заклинивание'
        }
    },
    5: {'type': 'standard', 'text': 'Работа двигателя', 'fault_options': {'shum_gul': 'Посторонний шум/гул', 'stuk': 'Посторонний стук', 'troenie': 'Неровная работа/троение'}},
    'pause_2': {'type': 'pause', 'text': 'Проверьте внешние осветительные приборы'},
    6: {'type': 'standard', 'text': 'Габариты', 'is_multi_select': True, 'fault_options': {'pered_lev': 'Передний левый', 'pered_prav': 'Передний правый', 'zad_lev': 'Задний левый', 'zad_прав': 'Задний правый'}},
    7: {'type': 'standard', 'text': 'Ближний свет', 'is_multi_select': True, 'fault_options': {'lev': 'Слева', 'prav': 'Справа'}},
    8: {'type': 'standard', 'text': 'Дальний свет', 'is_multi_select': True, 'fault_options': {'lev': 'Слева', 'prav': 'Справа'}},
    9: {'type': 'standard', 'text': 'Противотуманные фары', 'is_multi_select': True, 'fault_options': {'pered_lev': 'Передний левый', 'pered_prav': 'Передний правый', 'zad_lev': 'Задний левый', 'zad_прав': 'Задний правый'}},
    10: {'type': 'standard', 'text': 'Указатель поворотов', 'is_multi_select': True, 'fault_options': {'pered_lev': 'Передний левый', 'pered_prav': 'Передний правый', 'zad_lev': 'Задний левый', 'zad_prav': 'Задний правый', 'dop_lev': 'Дополнительный слева', 'dop_prav': 'Дополнительный справа'}},
    11: {'type': 'standard', 'text': 'Стоп сигналы', 'is_multi_select': True, 'fault_options': {'lev': 'Слева', 'prav': 'Справа', 'central': 'Центральный'}},
    12: {'type': 'standard', 'text': 'Сигнал заднего хода'},
    13: {'type': 'standard', 'text': 'Подсветка номера', 'is_multi_select': True, 'fault_options': {'lev': 'Слева', 'prav': 'Справа'}},
    14: {'type': 'standard', 'text': 'Проверьте состояние приводных ремней', 'is_multi_select': True, 'fault_options': {'remen_gen': 'Ремень генератора', 'remen_gur': 'Ремень ГУР', 'remen_cond': 'Ремень кондиционера', 'remen_pompy': 'Ремень помпы'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'otsloeniya': 'Отслоения', 'popadanie_masla': 'Попадание масла'}}},
    15: {'type': 'standard', 'text': 'Проверьте состояние воздушного фильтра', 'fault_options': {'zagryaznen': 'Загрязнен', 'vlaga': 'Попадание влаги', 'treb_razbor': 'Требуется доп. разбор'}},
    16: {'type': 'standard', 'text': 'Проверьте состояние салонного фильтра', 'fault_options': {'zagryaznen': 'Загрязнен', 'vlaga': 'Попадание влаги', 'otsutstvuet': 'Отсутствует', 'treb_razbor': 'Требуется доп. разбор'}},
    'pause_3': {'type': 'pause', 'text': 'Проверьте состояние и уровень технических жидкостей'},
    17: {'type': 'choice', 'text': 'Уровень масла двигателя', 'options': {'uroven': 'Уровень', 'nizhe': 'Ниже уровня', 'vyshe': 'Выше уровня'}, 'fault_choices': ['nizhe', 'vyshe']},
    18: {'type': 'choice', 'text': 'Состояние масла двигателя', 'options': {'svezhee': 'Свежее', 'rabochee': 'Рабочее', 'primesi': 'С механическими примесями', 'antifriz': 'Следы антифриза', 'voda': 'Следы воды'}, 'fault_choices': ['primesi', 'antifriz', 'voda'], 'photo_logic': {'primesi': 'Приложите фото капельного теста', 'antifriz': 'Приложите фото капельного теста', 'voda': 'Приложите фото капельного теста'}},
    19: {'type': 'choice', 'text': 'Уровень масла ГУР', 'options': {'uroven': 'Уровень', 'nizhe': 'Ниже уровня', 'vyshe': 'Выше уровня'}, 'fault_choices': ['nizhe', 'vyshe']},
    20: {'type': 'choice', 'text': 'Состояние масла ГУР', 'options': {'svezhee': 'Свежее', 'rabochee': 'Рабочее', 'primesi': 'С механическими примесями', 'goreloe': 'Горелое', 'voda': 'Следы воды'}, 'fault_choices': ['primesi', 'goreloe', 'voda'], 'photo_logic': {'primesi': 'Приложите фото капельного теста', 'goreloe': 'Приложите фото капельного теста', 'voda': 'Приложите фото капельного теста'}},
    21: {'type': 'choice', 'text': 'Уровень масла АКПП', 'options': {'uroven': 'Уровень', 'nizhe': 'Ниже уровня', 'vyshe': 'Выше уровня', 'treb_razbor': 'Требуется дополнительный разбор'}, 'fault_choices': ['nizhe', 'vyshe', 'treb_razbor'], 'skip_logic': {'treb_razbor': [22]}},
    22: {'type': 'choice', 'text': 'Состояние масла АКПП', 'options': {'svezhee': 'Свежее', 'rabochee': 'Рабочее', 'primesi': 'С механическими примесями', 'goreloe': 'Горелое', 'voda': 'Следы воды'}, 'fault_choices': ['primesi', 'goreloe', 'voda'], 'photo_logic': {'primesi': 'Приложите фото капельного теста', 'goreloe': 'Приложите фото капельного теста', 'voda': 'Приложите фото капельного теста'}},
    23: {'type': 'choice', 'text': 'Уровень охлаждающей жидкости', 'options': {'uroven': 'Уровень', 'nizhe': 'Ниже уровня', 'vyshe': 'Выше уровня'}, 'fault_choices': ['nizhe', 'vyshe']},
    24: {'type': 'choice', 'text': 'Температура кристаллизации ОЖ', 'options': {'bolee_36': 'Более 36°', '30_35': '30-35°', '25_30': '25-30°', 'menee_25': 'Менее 25°'}, 'fault_choices': ['30_35', '25_30', 'menee_25']},
    25: {'type': 'choice', 'text': 'Уровень тормозной жидкости', 'options': {'uroven': 'Уровень', 'nizhe': 'Ниже уровня', 'vyshe': 'Выше уровня'}, 'fault_choices': ['nizhe', 'vyshe']},
    26: {'type': 'choice', 'text': 'Содержание влаги в тормозной жидкости', 'options': {'menee_1': 'Менее 1%', '1_2': '1%-2%', 'bolee_2': 'Более 2%'}, 'fault_choices': ['1_2', 'bolee_2']},
    28: {'type': 'choice', 'text': 'Укажите привод автомобиля', 'options': {'peredniy': 'Передний', 'zadniy': 'Задний', 'polniy': 'Полный'}, 'skip_logic': {'peredniy': [90, 91, 92], 'zadniy': [89, 90]}},
    55: {'type': 'standard', 'text': 'Подшипники ступиц передние', 'is_multi_select': True, 'fault_options': {'lev': 'Левый', 'prav': 'Правый'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'shum': 'Шум', 'lyuft': 'Люфт'}}},
    'pause_4': {'type': 'pause', 'text': 'Проверьте состояние передних тормозов'},
    29: {'type': 'choice', 'text': 'Износ передних тормозных дисков', 'options': {'ravnomerniy': 'Равномерный', 'neravnomerniy_lev': 'Больший износ слева', 'neravnomerniy_prav': 'Больший износ справа'}, 'fault_choices': ['neravnomerniy_lev', 'neravnomerniy_prav']},
    30: {'type': 'choice', 'text': 'Износ передних тормозных дисков (толщина)', 'options': {'menee_1': 'Менее 1мм (<25%)', '1_2': '1-2мм (25-50%)', '2_3': '2-3мм (50-75%)', 'bolee_3': 'Более 3мм (>75%)'}, 'fault_choices': ['1_2', '2_3', 'bolee_3']},
    31: {'type': 'choice', 'text': 'Износ передних тормозных колодок', 'options': {'ravnomerniy': 'Равномерный', 'neravnomerniy_lev': 'Больший износ слева', 'neravnomerniy_prav': 'Больший износ справа'}, 'fault_choices': ['neravnomerniy_lev', 'neravnomerniy_prav']},
    32: {'type': 'choice', 'text': 'Остаток передних тормозных колодок', 'options': {'bolee_5': 'Более 5мм (<25%)', '4_5': '4-5мм (25-50%)', '3_4': '3-4мм (50-75%)', 'menee_3': 'Менее 3мм (>75%)'}, 'fault_choices': ['4_5', '3_4', 'menee_3']},
    33: {'type': 'standard', 'text': 'Состояние передних тормозных шлангов', 'is_multi_select': True, 'fault_options': {'lev': 'Слева', 'prav': 'Справа', 'oba': 'Оба'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'povrezhdenie': 'Механические повреждения', 'vzdutie': 'Вздутие', 'tech': 'Течь'}}},
    34: {'type': 'standard', 'text': 'Состояние передних тормозных трубок', 'is_multi_select': True, 'fault_options': {'lev': 'Слева', 'prav': 'Справа', 'obe': 'Обе'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'povrezhdenie': 'Механические повреждения', 'korroziya': 'Сильная коррозия', 'tech': 'Течь'}}},
    'pause_5': {'type': 'pause', 'text': 'Проверьте состояние задних тормозов'},
    35: {'type': 'choice', 'text': 'Износ задних тормозных дисков', 'options': {'ravnomerniy': 'Равномерный', 'barabanniy': 'Барабанный тормоз', 'neravnomerniy_lev': 'Больший износ слева', 'neravnomerniy_prav': 'Больший износ справа'}, 'fault_choices': ['neravnomerniy_lev', 'neravnomerniy_prav'], 'skip_logic': {'barabanniy': [36, 37, 38, 45, 46]}},
    36: {'type': 'choice', 'text': 'Износ задних тормозных дисков (толщина)', 'options': {'menee_1': 'Менее 1мм (<25%)', '1_2': '1-2мм (25-50%)', '2_3': '2-3мм (50-75%)', 'bolee_3': 'Более 3мм (>75%)'}, 'fault_choices': ['1_2', '2_3', 'bolee_3']},
    37: {'type': 'choice', 'text': 'Износ задних тормозных колодок', 'options': {'ravnomerniy': 'Равномерный', 'neravnomerniy_lev': 'Больший износ слева', 'neravnomerniy_prav': 'Больший износ справа'}, 'fault_choices': ['neravnomerniy_lev', 'neravnomerniy_prav']},
    38: {'type': 'choice', 'text': 'Остаток задних тормозных колодок', 'options': {'bolee_5': 'Более 5мм (<25%)', '4_5': '4-5мм (25-50%)', '3_4': '3-4мм (50-75%)', 'menee_3': 'Менее 3мм (>75%)'}, 'fault_choices': ['4_5', '3_4', 'menee_3']},
    39: {'type': 'standard', 'text': 'Состояние задних тормозных шлангов', 'is_multi_select': True, 'fault_options': {'lev': 'Слева', 'prav': 'Справа', 'oba': 'Оба'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'povrezhdenie': 'Механические повреждения', 'vzdutie': 'Вздутие', 'tech': 'Течь'}}},
    40: {'type': 'standard', 'text': 'Состояние задних тормозных трубок', 'is_multi_select': True, 'fault_options': {'lev': 'Слева', 'prav': 'Справа', 'obe': 'Обе'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'povrezhdenie': 'Механические повреждения', 'korroziya': 'Сильная коррозия', 'tech': 'Течь'}}},
    41: {'type': 'standard', 'text': 'Стояночный тормоз', 'skip_logic_if_ok': [42, 43, 44, 45, 46]},
    42: {'type': 'standard', 'text': 'Трос стояночного тормоза левый', 'fault_options': {'klinit': 'Клинит', 'porvan': 'Порван', 'rastyanut': 'Растянут', 'otsutstvuet': 'Отсутствует'}},
    43: {'type': 'standard', 'text': 'Трос стояночного тормоза правый', 'fault_options': {'klinit': 'Клинит', 'porvan': 'Порван', 'rastyanut': 'Растянут', 'otsutstvuet': 'Отсутствует'}},
    44: {'type': 'standard', 'text': 'Трос стояночного тормоза центральный', 'fault_options': {'klinit': 'Клинит', 'porvan': 'Порван', 'rastyanut': 'Растянут', 'otsutstvuet': 'Отсутствует'}},
    45: {'type': 'standard', 'text': 'Суппорт задний левый', 'fault_options': {'klinit_napr': 'Клинят направляющие', 'klinit_porsh': 'Клинит поршень'}},
    46: {'type': 'standard', 'text': 'Суппорт задний правый', 'fault_options': {'klinit_napr': 'Клинят направляющие', 'klinit_porsh': 'Клинит поршень'}},
    'pause_6': {'type': 'pause', 'text': 'Проверьте течи технических жидкостей'},
    47: {'type': 'standard', 'text': 'Течи моторного масла', 'default_ok': 'Нет течи', 'default_fault': 'Есть течь', 'is_multi_select': True, 'fault_options': {'tech_kl_kr': 'Течь клапанной крышки', 'tech_turbo': 'Течь турбокомпрессора', 'tech_poddona': 'Течь поддона', 'tech_pered_salnika': 'Течь переднего сальника КВ', 'tech_zad_salnika': 'Течь заднего сальника КВ', 'tech_ohl_masla': 'Течь охладителя масла'}},
    48: {'type': 'standard', 'text': 'Течи масла ГУР', 'default_ok': 'Нет течи', 'default_fault': 'Есть течь', 'is_multi_select': True, 'fault_options': {'tech_reiki': 'Течь рулевой рейки', 'tech_shlanga_vd': 'Течь шланга высокого давления', 'tech_shlanga_nd': 'Течь шланга низкого давления', 'tech_bachka': 'Течь бачка ГУР', 'tech_nasosa': 'Течь насоса ГУР'}},
    49: {'type': 'standard', 'text': 'Течи трансмиссионного масла', 'default_ok': 'Нет течи', 'default_fault': 'Есть течь', 'is_multi_select': True, 'fault_options': {'reduktor_pered': 'Редуктор переднего моста', 'razdatka': 'Раздаточная коробка', 'mufta_pp': 'Муфта полного привода', 'reduktor_zad': 'Редуктор заднего моста'}},
    50: {'type': 'standard', 'text': 'Течи масла АКПП/МКПП', 'default_ok': 'Нет течи', 'default_fault': 'Есть течь', 'is_multi_select': True, 'fault_options': {'tech_lev_salnika': 'Течь левого сальника КПП', 'tech_prav_salnika': 'Течь правого сальника КПП', 'tech_poddona': 'Течь поддона', 'tech_trubok': 'Течь трубок охлаждения КПП', 'tech_flanca': 'Течь фланца охлаждения/термостата'}},
    51: {'type': 'standard', 'text': 'Течи охлаждающей жидкости', 'default_ok': 'Нет течи', 'default_fault': 'Есть течь', 'is_multi_select': True, 'fault_options': {'tech_rad_osn': 'Течь радиатора основного', 'tech_rad_otop': 'Течь радиатора отопителя', 'tech_shlangov': 'Течь шлангов охлаждения', 'tech_pompy': 'Течь водяного насоса (помпы)'}},
    'pause_7': {'type': 'pause', 'text': 'Проверьте ходовую часть спереди'},
    52: {'type': 'standard', 'text': 'Амортизаторы передние', 'is_multi_select': True, 'fault_options': {'lev': 'Левый', 'prav': 'Правый'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'tech': 'Течь', 'zapotevanie': 'Запотевание', 'zvuk': 'Посторонний звук'}}},
    53: {'type': 'standard', 'text': 'Пружины передние', 'is_multi_select': True, 'fault_options': {'lev': 'Левая', 'prav': 'Правая'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'slomana': 'Сломана', 'prosela': 'Просела', 'zvuk': 'Посторонний звук'}}},
    54: {'type': 'standard', 'text': 'Опоры амортизаторов/подшипники передние', 'is_multi_select': True, 'fault_options': {'lev': 'Левая', 'prav': 'Правая'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'shum': 'Скрип/шум подшипника', 'opora_prosela': 'Опора просела'}}},
    56: {'type': 'choice', 'text': 'Укажите количество рычагов передней подвески', 'options': {'2': '2', '4': '4', '6': '6', '8': '8'}, 'skip_logic': {'2': list(range(60, 81)), '4': list(range(57, 60)) + list(range(65, 81)), '6': list(range(57, 65)) + list(range(72, 81)), '8': list(range(57, 72))}},
    57: {'type': 'standard', 'text': 'Шаровые опоры', 'is_multi_select': True, 'fault_options': {'lev': 'Левая', 'prav': 'Правая'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'lyuft': 'Люфт', 'porvan_pylnik': 'Порван пыльник'}}},
    58: {'type': 'standard', 'text': 'Сайлентблоки левого рычага', 'is_multi_select': True, 'fault_options': {'pered': 'Передний', 'zad': 'Задний'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    59: {'type': 'standard', 'text': 'Сайлентблоки правого рычага', 'is_multi_select': True, 'fault_options': {'pered': 'Передний', 'zad': 'Задний'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    60: {'type': 'standard', 'text': 'Шаровые опоры', 'is_multi_select': True, 'fault_options': {'nizh_lev': 'Нижняя левая', 'verh_lev': 'Верхняя левая', 'nizh_prav': 'Нижняя правая', 'verh_prav': 'Верхняя правая'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'lyuft': 'Люфт', 'porvan_pylnik': 'Порван пыльник'}}},
    61: {'type': 'standard', 'text': 'Сайлентблоки левого нижнего рычага', 'is_multi_select': True, 'fault_options': {'pered': 'Передний', 'zad': 'Задний'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    62: {'type': 'standard', 'text': 'Сайлентблоки левого верхнего рычага', 'is_multi_select': True, 'fault_options': {'pered': 'Передний', 'zad': 'Задний'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    63: {'type': 'standard', 'text': 'Сайлентблоки правого нижнего рычага', 'is_multi_select': True, 'fault_options': {'pered': 'Передний', 'zad': 'Задний'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    64: {'type': 'standard', 'text': 'Сайлентблоки правого верхнего рычага', 'is_multi_select': True, 'fault_options': {'pered': 'Передний', 'zad': 'Задний'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    65: {'type': 'standard', 'text': 'Шаровые опоры', 'is_multi_select': True, 'fault_options': {'lev_pered_nizh': 'Левого переднего нижнего рычага', 'lev_zad_nizh': 'Левого заднего нижнего рычага', 'lev_verh': 'Левого верхнего рычага', 'prav_pered_nizh': 'Правого переднего нижнего рычага'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'lyuft': 'Люфт', 'porvan_pylnik': 'Порван пыльник'}}},
    66: {'type': 'standard', 'text': 'Сайлентблок левого переднего нижнего рычага', 'fault_options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки', 'defect': 'Рычаг имеет дефект'}},
    67: {'type': 'standard', 'text': 'Сайлентблок левого заднего нижнего рычага', 'fault_options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки', 'defect': 'Рычаг имеет дефект'}},
    68: {'type': 'standard', 'text': 'Сайлентблоки левого верхнего рычага', 'is_multi_select': True, 'fault_options': {'pered': 'Передний', 'zad': 'Задний'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки', 'defect': 'Рычаг имеет дефект'}}},
    69: {'type': 'standard', 'text': 'Сайлентблок правого переднего нижнего рычага', 'fault_options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки', 'defect': 'Рычаг имеет дефект'}},
    70: {'type': 'standard', 'text': 'Сайлентблок правого заднего нижнего рычага', 'fault_options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки', 'defect': 'Рычаг имеет дефект'}},
    71: {'type': 'standard', 'text': 'Сайлентблоки правого верхнего рычага', 'is_multi_select': True, 'fault_options': {'pered': 'Передний', 'zad': 'Задний'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки', 'defect': 'Рычаг имеет дефект'}}},
    72: {'type': 'standard', 'text': 'Шаровые опоры', 'is_multi_select': True, 'fault_options': {'lev_pered_nizh': 'Левого переднего нижнего', 'lev_zad_nizh': 'Левого заднего нижнего', 'lev_pered_verh': 'Левого переднего верхнего', 'lev_zad_verh': 'Левого заднего верхнего'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'lyuft': 'Люфт', 'porvan_pylnik': 'Порван пыльник'}}},
    73: {'type': 'standard', 'text': 'Сайлентблок левого переднего нижнего рычага', 'fault_options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки', 'defect': 'Рычаг имеет дефект'}},
    74: {'type': 'standard', 'text': 'Сайлентблок левого заднего нижнего рычага', 'fault_options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки', 'defect': 'Рычаг имеет дефект'}},
    75: {'type': 'standard', 'text': 'Сайлентблок левого переднего верхнего рычага', 'fault_options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки', 'defect': 'Рычаг имеет дефект'}},
    76: {'type': 'standard', 'text': 'Сайлентблок левого заднего верхнего рычага', 'fault_options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки', 'defect': 'Рычаг имеет дефект'}},
    77: {'type': 'standard', 'text': 'Сайлентблок правого переднего нижнего рычага', 'fault_options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки', 'defect': 'Рычаг имеет дефект'}},
    78: {'type': 'standard', 'text': 'Сайлентблок правого заднего нижнего рычага', 'fault_options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки', 'defect': 'Рычаг имеет дефект'}},
    79: {'type': 'standard', 'text': 'Сайлентблок правого переднего верхнего рычага', 'fault_options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки', 'defect': 'Рычаг имеет дефект'}},
    80: {'type': 'standard', 'text': 'Сайлентблок правого заднего верхнего рычага', 'fault_options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки', 'defect': 'Рычаг имеет дефект'}},
    81: {'type': 'standard', 'text': 'Сайлентблоки переднего подрамника', 'is_multi_select': True, 'fault_options': {'pered_lev': 'Передний левый', 'pered_prav': 'Передний правый', 'centr_lev': 'Центральный левый', 'centr_prav': 'Центральный правый'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    82: {'type': 'standard', 'text': 'Стойки переднего стабилизатора', 'is_multi_select': True, 'fault_options': {'lev': 'Левая', 'prav': 'Правая'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'stuk': 'Стук', 'lyuft': 'Люфт', 'otsutstvuet': 'Отсутствует'}}},
    83: {'type': 'standard', 'text': 'Втулки переднего стабилизатора', 'is_multi_select': True, 'fault_options': {'lev': 'Левая', 'prav': 'Правая'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'stuk': 'Стук', 'lyuft': 'Люфт'}}},
    'pause_8': {'type': 'pause', 'text': 'Проверьте рулевое управление'},
    84: {'type': 'standard', 'text': 'Рейка рулевая', 'fault_options': {'lyuft': 'Люфт', 'stuk': 'Стук', 'tech': 'Течь'}},
    85: {'type': 'standard', 'text': 'Тяги рулевые', 'is_multi_select': True, 'fault_options': {'lev': 'Левая', 'prav': 'Правая'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'stuk': 'Стук', 'lyuft': 'Люфт'}}},
    86: {'type': 'standard', 'text': 'Наконечники рулевые', 'is_multi_select': True, 'fault_options': {'lev': 'Левая', 'prav': 'Правая'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'stuk': 'Стук', 'lyuft': 'Люфт'}}},
    87: {'type': 'standard', 'text': 'Крестовины рулевого вала', 'is_multi_select': True, 'fault_options': {'verh': 'Верхняя', 'centr': 'Центральная', 'nizh': 'Нижняя'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'stuk': 'Стук', 'lyuft': 'Люфт'}}},
    88: {'type': 'standard', 'text': 'Проверьте опоры ДВС/КПП', 'is_multi_select': True, 'fault_options': {'lev': 'Левая', 'prav': 'Правая', 'pered': 'Передняя', 'zad': 'Задняя'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'prosela': 'Просела', 'otsloenie': 'Отслоение втулки'}}},
    'pause_9': {'type': 'pause', 'text': 'Проверьте трансмиссию'},
    89: {'type': 'standard', 'text': 'ШРУСа (пыльники) передние', 'is_multi_select': True, 'fault_options': {'lev_nar': 'Левый наружный', 'lev_vnut': 'Левый внутренний', 'prav_vnut': 'Правый внутренний', 'prav_nar': 'Правый наружный', 'podshipnik': 'Подшипник промежуточный'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'lyuft_stuk': 'Люфт/стук', 'porvan_pylnik': 'Порван пыльник', 'narush_germ': 'Нарушена герметичность', 'gul': 'Гул'}}},
    90: {'type': 'standard', 'text': 'Вал карданный передний', 'is_multi_select': True, 'fault_options': {'mufta_pered': 'Муфта передняя', 'krest_pered': 'Крестовина передняя', 'krest_zad': 'Крестовина задняя', 'mufta_zad': 'Муфта задняя'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'lyuft_stuk': 'Люфт/стук', 'rassloenie': 'Расслоение'}}},
    91: {'type': 'standard', 'text': 'Вал карданный задний', 'is_multi_select': True, 'fault_options': {'mufta_pered': 'Муфта передняя', 'krest_pered': 'Крестовина передняя', 'podshipnik': 'Подшипник подвесной', 'krest_zad': 'Крестовина задняя', 'mufta_zad': 'Муфта задняя'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'lyuft_stuk': 'Люфт/стук', 'rassloenie': 'Расслоение', 'gul': 'Гул'}}},
    92: {'type': 'standard', 'text': 'ШРУСа (пыльники) задние', 'is_multi_select': True, 'fault_options': {'lev_nar': 'Левый наружный', 'lev_vnut': 'Левый внутренний', 'prav_vnut': 'Правый внутренний', 'prav_nar': 'Правый наружный'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'lyuft_stuk': 'Люфт/стук', 'porvan_pylnik': 'Порван пыльник', 'narush_germ': 'Нарушена герметичность'}}},
    'pause_10': {'type': 'pause', 'text': 'Проверьте ходовую часть сзади'},
    93: {'type': 'standard', 'text': 'Амортизаторы задние', 'is_multi_select': True, 'fault_options': {'lev': 'Левый', 'prav': 'Правый'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'tech': 'Течь', 'zapotevanie': 'Запотевание', 'zvuk': 'Посторонний звук'}}},
    94: {'type': 'standard', 'text': 'Пружины задние', 'is_multi_select': True, 'fault_options': {'lev': 'Левая', 'prav': 'Правая'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'slomana': 'Сломана', 'prosela': 'Просела', 'zvuk': 'Посторонний звук'}}},
    95: {'type': 'standard', 'text': 'Опоры амортизаторов задние', 'is_multi_select': True, 'fault_options': {'lev': 'Левая', 'prav': 'Правая'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'shum': 'Скрип/шум подшипника', 'opora_prosela': 'Опора просела'}}},
    96: {'type': 'standard', 'text': 'Подшипники ступиц задние', 'is_multi_select': True, 'fault_options': {'lev': 'Левый', 'prav': 'Правый'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'shum': 'Шум', 'lyuft': 'Люфт'}}},
    97: {'type': 'choice', 'text': 'Укажите количество рычагов задней подвески', 'options': {'balka': 'Балка', '6': '6', '8': '8', '10': '10'}, 'skip_logic': {'balka': list(range(99, 131)), '6': [98] + list(range(107, 129)), '8': [98] + list(range(99, 107)) + list(range(117, 129)), '10': [98] + list(range(99, 117))}},
    98: {'type': 'standard', 'text': 'Сайлентблоки балки', 'is_multi_select': True, 'fault_options': {'lev': 'Левый', 'prav': 'Правый'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки', 'defect': 'Балка имеет дефект'}}},
    99: {'type': 'standard', 'text': 'Сайлентблоки левого продольного рычага', 'is_multi_select': True, 'fault_options': {'pered_kuzov': 'Передний (к кузову)', 'zad_kulak': 'Задний (к кулаку)'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    100: {'type': 'standard', 'text': 'Сайлентблоки левого поперечного переднего рычага', 'is_multi_select': True, 'fault_options': {'pered_kuzov': 'Передний (к кузову)', 'zad_kulak': 'Задний (к кулаку)'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    101: {'type': 'standard', 'text': 'Сайлентблоки левого поперечного заднего рычага', 'is_multi_select': True, 'fault_options': {'pered_kuzov': 'Передний (к кузову)', 'zad_kulak': 'Задний (к кулаку)'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    102: {'type': 'standard', 'text': 'Сайлентблоки правого продольного рычага', 'is_multi_select': True, 'fault_options': {'pered_kuzov': 'Передний (к кузову)', 'zad_kulak': 'Задний (к кулаку)'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    103: {'type': 'standard', 'text': 'Сайлентблоки правого поперечного переднего рычага', 'is_multi_select': True, 'fault_options': {'pered_kuzov': 'Передний (к кузову)', 'zad_kulak': 'Задний (к кулаку)'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    104: {'type': 'standard', 'text': 'Сайлентблоки правого поперечного заднего рычага', 'is_multi_select': True, 'fault_options': {'pered_kuzov': 'Передний (к кузову)', 'zad_kulak': 'Задний (к кулаку)'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    105: {'type': 'standard', 'text': 'Сайлентблоки кулака', 'is_multi_select': True, 'fault_options': {'lev': 'Левого', 'prav': 'Правого'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    106: {'type': 'standard', 'text': 'Сайлентблоки заднего подрамника', 'is_multi_select': True, 'fault_options': {'pered_lev': 'Передний левый', 'pered_prav': 'Передний правый', 'centr_lev': 'Центральный левый', 'centr_prav': 'Центральный правый'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    107: {'type': 'standard', 'text': 'Сайлентблоки левого продольного рычага', 'is_multi_select': True, 'fault_options': {'pered_kuzov': 'Передний (к кузову)', 'zad_kulak': 'Задний (к кулаку)'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    108: {'type': 'standard', 'text': 'Сайлентблоки левого поперечного нижнего рычага', 'is_multi_select': True, 'fault_options': {'pered_kuzov': 'Передний (к кузову)', 'zad_kulak': 'Задний (к кулаку)'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    109: {'type': 'standard', 'text': 'Сайлентблоки левого поперечного верхнего рычага', 'is_multi_select': True, 'fault_options': {'pered_kuzov': 'Передний (к кузову)', 'zad_kulak': 'Задний (к кулаку)'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    110: {'type': 'standard', 'text': 'Сайлентблоки левой тяги', 'is_multi_select': True, 'fault_options': {'pered_kuzov': 'Передний (к кузову)', 'zad_kulak': 'Задний (к кулаку)'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    111: {'type': 'standard', 'text': 'Сайлентблоки правого продольного рычага', 'is_multi_select': True, 'fault_options': {'pered_kuzov': 'Передний (к кузову)', 'zad_kulak': 'Задний (к кулаку)'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    112: {'type': 'standard', 'text': 'Сайлентблоки правого поперечного нижнего рычага', 'is_multi_select': True, 'fault_options': {'pered_kuzov': 'Передний (к кузову)', 'zad_kulak': 'Задний (к кулаку)'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    113: {'type': 'standard', 'text': 'Сайлентблоки правого поперечного верхнего рычага', 'is_multi_select': True, 'fault_options': {'pered_kuzov': 'Передний (к кузову)', 'zad_kulak': 'Задний (к кулаку)'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    114: {'type': 'standard', 'text': 'Сайлентблоки правой тяги', 'is_multi_select': True, 'fault_options': {'pered_kuzov': 'Передний (к кузову)', 'zad_kulak': 'Задний (к кулаку)'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    115: {'type': 'standard', 'text': 'Сайлентблоки кулака', 'is_multi_select': True, 'fault_options': {'lev': 'Левого', 'prav': 'Правого'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    116: {'type': 'standard', 'text': 'Сайлентблоки заднего подрамника', 'is_multi_select': True, 'fault_options': {'pered_lev': 'Передний левый', 'pered_prav': 'Передний правый', 'centr_lev': 'Центральный левый', 'centr_prav': 'Центральный правый'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    117: {'type': 'standard', 'text': 'Сайлентблоки левого продольного нижнего рычага', 'is_multi_select': True, 'fault_options': {'pered_kuzov': 'Передний (к кузову)', 'zad_kulak': 'Задний (к кулаку)'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    118: {'type': 'standard', 'text': 'Сайлентблоки левого продольного верхнего рычага', 'is_multi_select': True, 'fault_options': {'pered_kuzov': 'Передний (к кузову)', 'zad_kulak': 'Задний (к кулаку)'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    119: {'type': 'standard', 'text': 'Сайлентблоки левого поперечного нижнего рычага', 'is_multi_select': True, 'fault_options': {'pered_kuzov': 'Передний (к кузову)', 'zad_kulak': 'Задний (к кулаку)'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    120: {'type': 'standard', 'text': 'Сайлентблоки левого поперечного верхнего рычага', 'is_multi_select': True, 'fault_options': {'pered_kuzov': 'Передний (к кузову)', 'zad_kulak': 'Задний (к кулаку)'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    121: {'type': 'standard', 'text': 'Сайлентблоки левой тяги', 'is_multi_select': True, 'fault_options': {'pered_kuzov': 'Передний (к кузову)', 'zad_kulak': 'Задний (к кулаку)'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    122: {'type': 'standard', 'text': 'Сайлентблоки правого продольного нижнего рычага', 'is_multi_select': True, 'fault_options': {'pered_kuzov': 'Передний (к кузову)', 'zad_kulak': 'Задний (к кулаку)'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    123: {'type': 'standard', 'text': 'Сайлентблоки правого продольного верхнего рычага', 'is_multi_select': True, 'fault_options': {'pered_kuzov': 'Передний (к кузову)', 'zad_kulak': 'Задний (к кулаку)'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    124: {'type': 'standard', 'text': 'Сайлентблоки правого поперечного нижнего рычага', 'is_multi_select': True, 'fault_options': {'pered_kuzov': 'Передний (к кузову)', 'zad_kulak': 'Задний (к кулаку)'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    125: {'type': 'standard', 'text': 'Сайлентблоки правого поперечного верхнего рычага', 'is_multi_select': True, 'fault_options': {'pered_kuzov': 'Передний (к кузову)', 'zad_kulak': 'Задний (к кулаку)'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    126: {'type': 'standard', 'text': 'Сайлентблоки правой тяги', 'is_multi_select': True, 'fault_options': {'pered_kuzov': 'Передний (к кузову)', 'zad_kulak': 'Задний (к кулаку)'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    127: {'type': 'standard', 'text': 'Сайлентблоки кулака', 'is_multi_select': True, 'fault_options': {'lev': 'Левого', 'prav': 'Правого'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    128: {'type': 'standard', 'text': 'Сайлентблоки заднего подрамника', 'is_multi_select': True, 'fault_options': {'pered_lev': 'Передний левый', 'pered_prav': 'Передний правый', 'centr_lev': 'Центральный левый', 'centr_prav': 'Центральный правый'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'treshiny': 'Трещины', 'nadryvy': 'Надрывы', 'otsloenie': 'Отслоение втулки'}}},
    129: {'type': 'standard', 'text': 'Стойки заднего стабилизатора', 'is_multi_select': True, 'fault_options': {'lev': 'Левая', 'prav': 'Правая'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'stuk': 'Стук', 'lyuft': 'Люфт', 'otsutstvuet': 'Отсутствует'}}},
    130: {'type': 'standard', 'text': 'Втулки заднего стабилизатора', 'is_multi_select': True, 'fault_options': {'lev': 'Левая', 'prav': 'Правая'}, 'sub_questions': {'text': 'Уточните неисправность для "{option_text}":', 'options': {'stuk': 'Стук', 'lyuft': 'Люфт'}}},
    'pause_11': {'type': 'pause', 'text': 'Проверьте выхлопную систему'},
    131: {'type': 'standard', 'text': 'Гофра', 'fault_options': {'free_input': 'Укажите количество и размеры'}},
    132: {'type': 'standard', 'text': 'Фланец глушителя', 'fault_options': {'free_input': 'Укажите количество и размеры'}},
    133: {'type': 'standard', 'text': 'Хомут глушителя', 'fault_options': {'free_input': 'Укажите количество и размеры'}},
    134: {'type': 'standard', 'text': 'Крепления глушителя', 'fault_options': {'free_input': 'Укажите количество'}},
    135: {'type': 'standard', 'text': 'Подвесы глушителя', 'fault_options': {'free_input': 'Укажите количество'}},
    136: {'type': 'standard', 'text': 'Резонатор глушителя'},
    137: {'type': 'standard', 'text': 'Задняя банка глушителя'},
    'final_remarks': {'type': 'standard', 'text': 'Иные замечания'}
}

# --- связывание вопросов ---
flow_order = [
    1, 2, 3, 'pause_1', 4, 5, 'pause_2', 6, 7, 8, 9, 10, 11, 12, 13,
    14, 15, 16, 'pause_3', 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 28,
    55, 'pause_4', 29, 30, 31, 32, 33, 34, 'pause_5', 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
    'pause_6', 47, 48, 49, 50, 51, 'pause_7', 52, 53, 54, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
    66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 'pause_8', 84, 85, 86, 87, 88,
    'pause_9', 89, 90, 91, 92, 'pause_10', 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106,
    107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
    126, 127, 128, 129, 130, 'pause_11', 131, 132, 133, 134, 135, 136, 137, 'final_remarks'
]

for i, q_id in enumerate(flow_order):

    if 'next_q' not in QUESTIONS[q_id]:
        if i + 1 < len(flow_order):
            QUESTIONS[q_id]['next_q'] = flow_order[i+1]
        else:
            # Последний вопрос ведет к завершению
            QUESTIONS[q_id]['next_q'] = 'END'